version: '3.8'

services:
  app:
    build: .
    ports:
      - "6898:8080"
    container_name: app_container
    volumes:
      - ./web:/home/myuser/web
      - ./localhost:/home/myuser/tomcat/apache-tomcat-9.0.73/conf/Catalina/localhost
    depends_on:
      - db

  db:
    image: mysql:5.7.41
    ports:
      - "3396:3306"
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d